services:
  - type: web
    name: sgc-pavi-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: sgc-pavi-backend
          property: port
    autoDeploy: true
    repo: https://github.com/GETINSOFT01/SGC-PAVI.git
    branch: main
    rootDir: backend
